dist: xenial
language: cpp
os: linux
matrix:
  include:
    - compiler: gcc
      env: GCC_VERSION=5 BUILD_TYPE=Release
      addons:
        apt:
          packages:
           - g++-5
    - compiler: gcc
      env: GCC_VERSION=6 BUILD_TYPE=Release
      addons:
        apt:
          packages:
           - g++-6
    - compiler: gcc
      env: GCC_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          packages:
           - g++-7
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          packages:
           - g++-8
           - clang-7
script:
  - make tests
  - test -z "$(awk '{print $1}' report | grep -v 0)"
after_failure:
  - cat tests/*diff
